/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.6/userguide/multi_project_builds.html
 */

rootProject.name = "aerospike-proxy-sdk"

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version ("0.7.0")
}

include("proto")
include("stub")

// Add prefix to child project names.
rootProject.children.forEach {
    it.name = "aerospike-proxy-" + it.name
}
